main: org.ultimatechat2.core.UltimateChatPlugin
version: 2.2.1
name: UltimateChat2
softdepend: [PlaceholderAPI, Factions, LegacyFactions, LuckPerms, MassiveCore]
depend: [Vault]
authors: [Lertu]
commands:
  ultimatechat:
    description: help
    usage: /<command>